// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/Alert/CadenceAlert.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout.Alert {

  /// <summary>Holder for reflection information generated from CustomWorkout/Alert/CadenceAlert.proto</summary>
  internal static partial class CadenceAlertReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/Alert/CadenceAlert.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CadenceAlertReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZDdXN0b21Xb3Jrb3V0L0FsZXJ0L0NhZGVuY2VBbGVydC5wcm90byK4AgoM",
            "Q2FkZW5jZUFsZXJ0EjwKE2NhZGVuY2VfcmFuZ2VfYWxlcnQYAiABKAsyHy5D",
            "YWRlbmNlQWxlcnQuQ2FkZW5jZVJhbmdlQWxlcnQadQoRQ2FkZW5jZVJhbmdl",
            "QWxlcnQSLwoLbG93ZXJfYm91bmQYASABKAsyGi5DYWRlbmNlQWxlcnQuQ2Fk",
            "ZW5jZUJvdW5kEi8KC3VwcGVyX2JvdW5kGAIgASgLMhouQ2FkZW5jZUFsZXJ0",
            "LkNhZGVuY2VCb3VuZBpKCgxDYWRlbmNlQm91bmQSDwoHY2FkZW5jZRgBIAEo",
            "DRIpCgl0aW1lX3VuaXQYAiABKAsyFi5DYWRlbmNlQWxlcnQuVGltZVVuaXQa",
            "JwoIVGltZVVuaXQSDAoEdW5pdBgBIAEoDRINCgV2YWx1ZRgCIAEoAUIwqgIt",
            "RG90bmV0V29ya291dEtpdC5Qcm90b2J1Zi5DdXN0b21Xb3Jrb3V0LkFsZXJ0",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Parser, new[]{ "CadenceRangeAlert" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert.Parser, new[]{ "LowerBound", "UpperBound" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound.Parser, new[]{ "Cadence", "TimeUnit" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit.Parser, new[]{ "Unit", "Value" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class CadenceAlert : pb::IMessage<CadenceAlert>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CadenceAlert> _parser = new pb::MessageParser<CadenceAlert>(() => new CadenceAlert());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CadenceAlert> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlertReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CadenceAlert() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CadenceAlert(CadenceAlert other) : this() {
      cadenceRangeAlert_ = other.cadenceRangeAlert_ != null ? other.cadenceRangeAlert_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CadenceAlert Clone() {
      return new CadenceAlert(this);
    }

    /// <summary>Field number for the "cadence_range_alert" field.</summary>
    public const int CadenceRangeAlertFieldNumber = 2;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert cadenceRangeAlert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert CadenceRangeAlert {
      get { return cadenceRangeAlert_; }
      set {
        cadenceRangeAlert_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CadenceAlert);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CadenceAlert other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CadenceRangeAlert, other.CadenceRangeAlert)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (cadenceRangeAlert_ != null) hash ^= CadenceRangeAlert.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (cadenceRangeAlert_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CadenceRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (cadenceRangeAlert_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CadenceRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (cadenceRangeAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CadenceRangeAlert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CadenceAlert other) {
      if (other == null) {
        return;
      }
      if (other.cadenceRangeAlert_ != null) {
        if (cadenceRangeAlert_ == null) {
          CadenceRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert();
        }
        CadenceRangeAlert.MergeFrom(other.CadenceRangeAlert);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (cadenceRangeAlert_ == null) {
              CadenceRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert();
            }
            input.ReadMessage(CadenceRangeAlert);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (cadenceRangeAlert_ == null) {
              CadenceRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceRangeAlert();
            }
            input.ReadMessage(CadenceRangeAlert);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CadenceAlert message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class CadenceRangeAlert : pb::IMessage<CadenceRangeAlert>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CadenceRangeAlert> _parser = new pb::MessageParser<CadenceRangeAlert>(() => new CadenceRangeAlert());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CadenceRangeAlert> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceRangeAlert() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceRangeAlert(CadenceRangeAlert other) : this() {
          lowerBound_ = other.lowerBound_ != null ? other.lowerBound_.Clone() : null;
          upperBound_ = other.upperBound_ != null ? other.upperBound_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceRangeAlert Clone() {
          return new CadenceRangeAlert(this);
        }

        /// <summary>Field number for the "lower_bound" field.</summary>
        public const int LowerBoundFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound lowerBound_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound LowerBound {
          get { return lowerBound_; }
          set {
            lowerBound_ = value;
          }
        }

        /// <summary>Field number for the "upper_bound" field.</summary>
        public const int UpperBoundFieldNumber = 2;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound upperBound_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound UpperBound {
          get { return upperBound_; }
          set {
            upperBound_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CadenceRangeAlert);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CadenceRangeAlert other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(LowerBound, other.LowerBound)) return false;
          if (!object.Equals(UpperBound, other.UpperBound)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (lowerBound_ != null) hash ^= LowerBound.GetHashCode();
          if (upperBound_ != null) hash ^= UpperBound.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (lowerBound_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LowerBound);
          }
          if (upperBound_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(UpperBound);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (lowerBound_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LowerBound);
          }
          if (upperBound_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(UpperBound);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (lowerBound_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(LowerBound);
          }
          if (upperBound_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpperBound);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CadenceRangeAlert other) {
          if (other == null) {
            return;
          }
          if (other.lowerBound_ != null) {
            if (lowerBound_ == null) {
              LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
            }
            LowerBound.MergeFrom(other.LowerBound);
          }
          if (other.upperBound_ != null) {
            if (upperBound_ == null) {
              UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
            }
            UpperBound.MergeFrom(other.UpperBound);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (lowerBound_ == null) {
                  LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
                }
                input.ReadMessage(LowerBound);
                break;
              }
              case 18: {
                if (upperBound_ == null) {
                  UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
                }
                input.ReadMessage(UpperBound);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (lowerBound_ == null) {
                  LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
                }
                input.ReadMessage(LowerBound);
                break;
              }
              case 18: {
                if (upperBound_ == null) {
                  UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.CadenceBound();
                }
                input.ReadMessage(UpperBound);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class CadenceBound : pb::IMessage<CadenceBound>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CadenceBound> _parser = new pb::MessageParser<CadenceBound>(() => new CadenceBound());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CadenceBound> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceBound() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceBound(CadenceBound other) : this() {
          cadence_ = other.cadence_;
          timeUnit_ = other.timeUnit_ != null ? other.timeUnit_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CadenceBound Clone() {
          return new CadenceBound(this);
        }

        /// <summary>Field number for the "cadence" field.</summary>
        public const int CadenceFieldNumber = 1;
        private uint cadence_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Cadence {
          get { return cadence_; }
          set {
            cadence_ = value;
          }
        }

        /// <summary>Field number for the "time_unit" field.</summary>
        public const int TimeUnitFieldNumber = 2;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit timeUnit_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit TimeUnit {
          get { return timeUnit_; }
          set {
            timeUnit_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CadenceBound);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CadenceBound other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Cadence != other.Cadence) return false;
          if (!object.Equals(TimeUnit, other.TimeUnit)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Cadence != 0) hash ^= Cadence.GetHashCode();
          if (timeUnit_ != null) hash ^= TimeUnit.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Cadence != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(Cadence);
          }
          if (timeUnit_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(TimeUnit);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Cadence != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(Cadence);
          }
          if (timeUnit_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(TimeUnit);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Cadence != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Cadence);
          }
          if (timeUnit_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeUnit);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CadenceBound other) {
          if (other == null) {
            return;
          }
          if (other.Cadence != 0) {
            Cadence = other.Cadence;
          }
          if (other.timeUnit_ != null) {
            if (timeUnit_ == null) {
              TimeUnit = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit();
            }
            TimeUnit.MergeFrom(other.TimeUnit);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Cadence = input.ReadUInt32();
                break;
              }
              case 18: {
                if (timeUnit_ == null) {
                  TimeUnit = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit();
                }
                input.ReadMessage(TimeUnit);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Cadence = input.ReadUInt32();
                break;
              }
              case 18: {
                if (timeUnit_ == null) {
                  TimeUnit = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Types.TimeUnit();
                }
                input.ReadMessage(TimeUnit);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class TimeUnit : pb::IMessage<TimeUnit>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TimeUnit> _parser = new pb::MessageParser<TimeUnit>(() => new TimeUnit());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TimeUnit> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeUnit() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeUnit(TimeUnit other) : this() {
          unit_ = other.unit_;
          value_ = other.value_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeUnit Clone() {
          return new TimeUnit(this);
        }

        /// <summary>Field number for the "unit" field.</summary>
        public const int UnitFieldNumber = 1;
        private uint unit_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Unit {
          get { return unit_; }
          set {
            unit_ = value;
          }
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 2;
        private double value_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Value {
          get { return value_; }
          set {
            value_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TimeUnit);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TimeUnit other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unit != other.Unit) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Unit != 0) hash ^= Unit.GetHashCode();
          if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Unit != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(Unit);
          }
          if (Value != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Unit != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(Unit);
          }
          if (Value != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Unit != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unit);
          }
          if (Value != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TimeUnit other) {
          if (other == null) {
            return;
          }
          if (other.Unit != 0) {
            Unit = other.Unit;
          }
          if (other.Value != 0D) {
            Value = other.Value;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Unit = input.ReadUInt32();
                break;
              }
              case 17: {
                Value = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Unit = input.ReadUInt32();
                break;
              }
              case 17: {
                Value = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
