// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/IntervalBlock.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout {

  /// <summary>Holder for reflection information generated from CustomWorkout/IntervalBlock.proto</summary>
  internal static partial class IntervalBlockReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/IntervalBlock.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IntervalBlockReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFDdXN0b21Xb3Jrb3V0L0ludGVydmFsQmxvY2sucHJvdG8aEVdvcmtvdXRT",
            "dGVwLnByb3RvIocCCg1JbnRlcnZhbEJsb2NrEjMKDmludGVydmFsX3N0ZXBz",
            "GAEgAygLMhsuSW50ZXJ2YWxCbG9jay5JbnRlcnZhbFN0ZXASEgoKaXRlcmF0",
            "aW9ucxgCIAEoDRqsAQoMSW50ZXJ2YWxTdGVwEjwKB3B1cnBvc2UYASABKA4y",
            "Ky5JbnRlcnZhbEJsb2NrLkludGVydmFsU3RlcC5JbnRlcnZhbFB1cnBvc2US",
            "IgoMd29ya291dF9zdGVwGAIgASgLMgwuV29ya291dFN0ZXAiOgoPSW50ZXJ2",
            "YWxQdXJwb3NlEg8KC1VOU1BFQ0lGSUVEEAASCAoEV09SSxABEgwKCFJFQ09W",
            "RVJZEAJCKqoCJ0RvdG5ldFdvcmtvdXRLaXQuUHJvdG9idWYuQ3VzdG9tV29y",
            "a291dGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStepReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock), global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Parser, new[]{ "IntervalSteps", "Iterations" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep), global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Parser, new[]{ "Purpose", "WorkoutStep" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class IntervalBlock : pb::IMessage<IntervalBlock>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntervalBlock> _parser = new pb::MessageParser<IntervalBlock>(() => new IntervalBlock());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IntervalBlock> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlockReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntervalBlock() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntervalBlock(IntervalBlock other) : this() {
      intervalSteps_ = other.intervalSteps_.Clone();
      iterations_ = other.iterations_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntervalBlock Clone() {
      return new IntervalBlock(this);
    }

    /// <summary>Field number for the "interval_steps" field.</summary>
    public const int IntervalStepsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep> _repeated_intervalSteps_codec
        = pb::FieldCodec.ForMessage(10, global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Parser);
    private readonly pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep> intervalSteps_ = new pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep>();
    /// <summary>
    /// IntervalStep
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep> IntervalSteps {
      get { return intervalSteps_; }
    }

    /// <summary>Field number for the "iterations" field.</summary>
    public const int IterationsFieldNumber = 2;
    private uint iterations_;
    /// <summary>
    /// Number of iterations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Iterations {
      get { return iterations_; }
      set {
        iterations_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IntervalBlock);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IntervalBlock other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!intervalSteps_.Equals(other.intervalSteps_)) return false;
      if (Iterations != other.Iterations) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= intervalSteps_.GetHashCode();
      if (Iterations != 0) hash ^= Iterations.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      intervalSteps_.WriteTo(output, _repeated_intervalSteps_codec);
      if (Iterations != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Iterations);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      intervalSteps_.WriteTo(ref output, _repeated_intervalSteps_codec);
      if (Iterations != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Iterations);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += intervalSteps_.CalculateSize(_repeated_intervalSteps_codec);
      if (Iterations != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Iterations);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IntervalBlock other) {
      if (other == null) {
        return;
      }
      intervalSteps_.Add(other.intervalSteps_);
      if (other.Iterations != 0) {
        Iterations = other.Iterations;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            intervalSteps_.AddEntriesFrom(input, _repeated_intervalSteps_codec);
            break;
          }
          case 16: {
            Iterations = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            intervalSteps_.AddEntriesFrom(ref input, _repeated_intervalSteps_codec);
            break;
          }
          case 16: {
            Iterations = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the IntervalBlock message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class IntervalStep : pb::IMessage<IntervalStep>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<IntervalStep> _parser = new pb::MessageParser<IntervalStep>(() => new IntervalStep());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<IntervalStep> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public IntervalStep() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public IntervalStep(IntervalStep other) : this() {
          purpose_ = other.purpose_;
          workoutStep_ = other.workoutStep_ != null ? other.workoutStep_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public IntervalStep Clone() {
          return new IntervalStep(this);
        }

        /// <summary>Field number for the "purpose" field.</summary>
        public const int PurposeFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose purpose_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified;
        /// <summary>
        /// IntervalPurpose
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose Purpose {
          get { return purpose_; }
          set {
            purpose_ = value;
          }
        }

        /// <summary>Field number for the "workout_step" field.</summary>
        public const int WorkoutStepFieldNumber = 2;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep workoutStep_;
        /// <summary>
        /// WorkoutStep
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep WorkoutStep {
          get { return workoutStep_; }
          set {
            workoutStep_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as IntervalStep);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(IntervalStep other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Purpose != other.Purpose) return false;
          if (!object.Equals(WorkoutStep, other.WorkoutStep)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Purpose != global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified) hash ^= Purpose.GetHashCode();
          if (workoutStep_ != null) hash ^= WorkoutStep.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Purpose != global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Purpose);
          }
          if (workoutStep_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(WorkoutStep);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Purpose != global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Purpose);
          }
          if (workoutStep_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(WorkoutStep);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Purpose != global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Purpose);
          }
          if (workoutStep_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorkoutStep);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(IntervalStep other) {
          if (other == null) {
            return;
          }
          if (other.Purpose != global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose.Unspecified) {
            Purpose = other.Purpose;
          }
          if (other.workoutStep_ != null) {
            if (workoutStep_ == null) {
              WorkoutStep = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
            }
            WorkoutStep.MergeFrom(other.WorkoutStep);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Purpose = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose) input.ReadEnum();
                break;
              }
              case 18: {
                if (workoutStep_ == null) {
                  WorkoutStep = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
                }
                input.ReadMessage(WorkoutStep);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Purpose = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Types.IntervalStep.Types.IntervalPurpose) input.ReadEnum();
                break;
              }
              case 18: {
                if (workoutStep_ == null) {
                  WorkoutStep = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
                }
                input.ReadMessage(WorkoutStep);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the IntervalStep message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          internal enum IntervalPurpose {
            /// <summary>
            /// Default value
            /// </summary>
            [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
            [pbr::OriginalName("WORK")] Work = 1,
            [pbr::OriginalName("RECOVERY")] Recovery = 2,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
