// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/Alert/WorkoutAlert.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout.Alert {

  /// <summary>Holder for reflection information generated from CustomWorkout/Alert/WorkoutAlert.proto</summary>
  internal static partial class WorkoutAlertReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/Alert/WorkoutAlert.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkoutAlertReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZDdXN0b21Xb3Jrb3V0L0FsZXJ0L1dvcmtvdXRBbGVydC5wcm90bxoQU3Bl",
            "ZWRBbGVydC5wcm90bxoZSGVhcnRSYXRlUmFuZ2VBbGVydC5wcm90bxoSQ2Fk",
            "ZW5jZUFsZXJ0LnByb3RvGhBQb3dlckFsZXJ0LnByb3RvIvwCCgxXb3Jrb3V0",
            "QWxlcnQSMwoMYWxlcnRfbWV0cmljGAEgASgOMh0uV29ya291dEFsZXJ0LkFs",
            "ZXJ0TWV0cmljRW51bRIPCgd1bmtub3duGAIgASgNEiAKC3NwZWVkX2FsZXJ0",
            "GAQgASgLMgsuU3BlZWRBbGVydBIkCg1jYWRlbmNlX2FsZXJ0GAUgASgLMg0u",
            "Q2FkZW5jZUFsZXJ0EiAKC3Bvd2VyX2FsZXJ0GAYgASgLMgsuUG93ZXJBbGVy",
            "dBI0ChZoZWFydF9yYXRlX3JhbmdlX2FsZXJ0GAcgASgLMhQuSGVhcnRSYXRl",
            "UmFuZ2VBbGVydCKFAQoPQWxlcnRNZXRyaWNFbnVtEg8KC1VOU1BFQ0lGSUVE",
            "EAASCwoHQVZFUkFHRRABEgsKB0NVUlJFTlQQAhILCgdDQURFTkNFEAMSEQoN",
            "UE9XRVJfQ1VSUkVOVBAEEhQKEENPVU5UX1BFUl9NSU5VVEUQBRIRCg1QT1dF",
            "Ul9BVkVSQUdFEAZCMKoCLURvdG5ldFdvcmtvdXRLaXQuUHJvdG9idWYuQ3Vz",
            "dG9tV29ya291dC5BbGVydGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlertReflection.Descriptor, global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlertReflection.Descriptor, global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlertReflection.Descriptor, global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlertReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Parser, new[]{ "AlertMetric", "Unknown", "SpeedAlert", "CadenceAlert", "PowerAlert", "HeartRateRangeAlert" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class WorkoutAlert : pb::IMessage<WorkoutAlert>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkoutAlert> _parser = new pb::MessageParser<WorkoutAlert>(() => new WorkoutAlert());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkoutAlert> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlertReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert(WorkoutAlert other) : this() {
      alertMetric_ = other.alertMetric_;
      unknown_ = other.unknown_;
      speedAlert_ = other.speedAlert_ != null ? other.speedAlert_.Clone() : null;
      cadenceAlert_ = other.cadenceAlert_ != null ? other.cadenceAlert_.Clone() : null;
      powerAlert_ = other.powerAlert_ != null ? other.powerAlert_.Clone() : null;
      heartRateRangeAlert_ = other.heartRateRangeAlert_ != null ? other.heartRateRangeAlert_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert Clone() {
      return new WorkoutAlert(this);
    }

    /// <summary>Field number for the "alert_metric" field.</summary>
    public const int AlertMetricFieldNumber = 1;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum alertMetric_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum AlertMetric {
      get { return alertMetric_; }
      set {
        alertMetric_ = value;
      }
    }

    /// <summary>Field number for the "unknown" field.</summary>
    public const int UnknownFieldNumber = 2;
    private uint unknown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unknown {
      get { return unknown_; }
      set {
        unknown_ = value;
      }
    }

    /// <summary>Field number for the "speed_alert" field.</summary>
    public const int SpeedAlertFieldNumber = 4;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert speedAlert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert SpeedAlert {
      get { return speedAlert_; }
      set {
        speedAlert_ = value;
      }
    }

    /// <summary>Field number for the "cadence_alert" field.</summary>
    public const int CadenceAlertFieldNumber = 5;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert cadenceAlert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert CadenceAlert {
      get { return cadenceAlert_; }
      set {
        cadenceAlert_ = value;
      }
    }

    /// <summary>Field number for the "power_alert" field.</summary>
    public const int PowerAlertFieldNumber = 6;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlert powerAlert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlert PowerAlert {
      get { return powerAlert_; }
      set {
        powerAlert_ = value;
      }
    }

    /// <summary>Field number for the "heart_rate_range_alert" field.</summary>
    public const int HeartRateRangeAlertFieldNumber = 7;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert heartRateRangeAlert_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert HeartRateRangeAlert {
      get { return heartRateRangeAlert_; }
      set {
        heartRateRangeAlert_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkoutAlert);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkoutAlert other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AlertMetric != other.AlertMetric) return false;
      if (Unknown != other.Unknown) return false;
      if (!object.Equals(SpeedAlert, other.SpeedAlert)) return false;
      if (!object.Equals(CadenceAlert, other.CadenceAlert)) return false;
      if (!object.Equals(PowerAlert, other.PowerAlert)) return false;
      if (!object.Equals(HeartRateRangeAlert, other.HeartRateRangeAlert)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) hash ^= AlertMetric.GetHashCode();
      if (Unknown != 0) hash ^= Unknown.GetHashCode();
      if (speedAlert_ != null) hash ^= SpeedAlert.GetHashCode();
      if (cadenceAlert_ != null) hash ^= CadenceAlert.GetHashCode();
      if (powerAlert_ != null) hash ^= PowerAlert.GetHashCode();
      if (heartRateRangeAlert_ != null) hash ^= HeartRateRangeAlert.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AlertMetric);
      }
      if (Unknown != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Unknown);
      }
      if (speedAlert_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SpeedAlert);
      }
      if (cadenceAlert_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CadenceAlert);
      }
      if (powerAlert_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PowerAlert);
      }
      if (heartRateRangeAlert_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AlertMetric);
      }
      if (Unknown != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Unknown);
      }
      if (speedAlert_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SpeedAlert);
      }
      if (cadenceAlert_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CadenceAlert);
      }
      if (powerAlert_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PowerAlert);
      }
      if (heartRateRangeAlert_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AlertMetric);
      }
      if (Unknown != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unknown);
      }
      if (speedAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpeedAlert);
      }
      if (cadenceAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CadenceAlert);
      }
      if (powerAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PowerAlert);
      }
      if (heartRateRangeAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkoutAlert other) {
      if (other == null) {
        return;
      }
      if (other.AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        AlertMetric = other.AlertMetric;
      }
      if (other.Unknown != 0) {
        Unknown = other.Unknown;
      }
      if (other.speedAlert_ != null) {
        if (speedAlert_ == null) {
          SpeedAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
        }
        SpeedAlert.MergeFrom(other.SpeedAlert);
      }
      if (other.cadenceAlert_ != null) {
        if (cadenceAlert_ == null) {
          CadenceAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert();
        }
        CadenceAlert.MergeFrom(other.CadenceAlert);
      }
      if (other.powerAlert_ != null) {
        if (powerAlert_ == null) {
          PowerAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlert();
        }
        PowerAlert.MergeFrom(other.PowerAlert);
      }
      if (other.heartRateRangeAlert_ != null) {
        if (heartRateRangeAlert_ == null) {
          HeartRateRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
        }
        HeartRateRangeAlert.MergeFrom(other.HeartRateRangeAlert);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AlertMetric = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) input.ReadEnum();
            break;
          }
          case 16: {
            Unknown = input.ReadUInt32();
            break;
          }
          case 34: {
            if (speedAlert_ == null) {
              SpeedAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
            }
            input.ReadMessage(SpeedAlert);
            break;
          }
          case 42: {
            if (cadenceAlert_ == null) {
              CadenceAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert();
            }
            input.ReadMessage(CadenceAlert);
            break;
          }
          case 50: {
            if (powerAlert_ == null) {
              PowerAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlert();
            }
            input.ReadMessage(PowerAlert);
            break;
          }
          case 58: {
            if (heartRateRangeAlert_ == null) {
              HeartRateRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
            }
            input.ReadMessage(HeartRateRangeAlert);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AlertMetric = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) input.ReadEnum();
            break;
          }
          case 16: {
            Unknown = input.ReadUInt32();
            break;
          }
          case 34: {
            if (speedAlert_ == null) {
              SpeedAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
            }
            input.ReadMessage(SpeedAlert);
            break;
          }
          case 42: {
            if (cadenceAlert_ == null) {
              CadenceAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.CadenceAlert();
            }
            input.ReadMessage(CadenceAlert);
            break;
          }
          case 50: {
            if (powerAlert_ == null) {
              PowerAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.PowerAlert();
            }
            input.ReadMessage(PowerAlert);
            break;
          }
          case 58: {
            if (heartRateRangeAlert_ == null) {
              HeartRateRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
            }
            input.ReadMessage(HeartRateRangeAlert);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the WorkoutAlert message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      internal enum AlertMetricEnum {
        [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("AVERAGE")] Average = 1,
        [pbr::OriginalName("CURRENT")] Current = 2,
        [pbr::OriginalName("CADENCE")] Cadence = 3,
        [pbr::OriginalName("POWER_CURRENT")] PowerCurrent = 4,
        [pbr::OriginalName("COUNT_PER_MINUTE")] CountPerMinute = 5,
        [pbr::OriginalName("POWER_AVERAGE")] PowerAverage = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
