// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorkoutFile.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf {

  /// <summary>Holder for reflection information generated from WorkoutFile.proto</summary>
  internal static partial class WorkoutFileReflection {

    #region Descriptor
    /// <summary>File descriptor for WorkoutFile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkoutFileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFXb3Jrb3V0RmlsZS5wcm90bxohQ3VzdG9tV29ya291dC9DdXN0b21Xb3Jr",
            "b3V0LnByb3RvImgKDVdvcmtvdXRCaW5hcnkSDAoER1VJRBgJIAEoCRImCg5j",
            "dXN0b21fd29ya291dBgLIAEoCzIOLkN1c3RvbVdvcmtvdXQSEAoHdmVyc2lv",
            "bhjoByABKA0SDwoGZm9ybWF0GOoHIAEoDUIcqgIZRG90bmV0V29ya291dEtp",
            "dC5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkoutReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.WorkoutBinary), global::DotnetWorkoutKit.Protobuf.WorkoutBinary.Parser, new[]{ "GUID", "CustomWorkout", "Version", "Format" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class WorkoutBinary : pb::IMessage<WorkoutBinary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkoutBinary> _parser = new pb::MessageParser<WorkoutBinary>(() => new WorkoutBinary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkoutBinary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.WorkoutFileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutBinary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutBinary(WorkoutBinary other) : this() {
      gUID_ = other.gUID_;
      customWorkout_ = other.customWorkout_ != null ? other.customWorkout_.Clone() : null;
      version_ = other.version_;
      format_ = other.format_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutBinary Clone() {
      return new WorkoutBinary(this);
    }

    /// <summary>Field number for the "GUID" field.</summary>
    public const int GUIDFieldNumber = 9;
    private string gUID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GUID {
      get { return gUID_; }
      set {
        gUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "custom_workout" field.</summary>
    public const int CustomWorkoutFieldNumber = 11;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout customWorkout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout CustomWorkout {
      get { return customWorkout_; }
      set {
        customWorkout_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1000;
    private uint version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "format" field.</summary>
    public const int FormatFieldNumber = 1002;
    private uint format_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Format {
      get { return format_; }
      set {
        format_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkoutBinary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkoutBinary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GUID != other.GUID) return false;
      if (!object.Equals(CustomWorkout, other.CustomWorkout)) return false;
      if (Version != other.Version) return false;
      if (Format != other.Format) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GUID.Length != 0) hash ^= GUID.GetHashCode();
      if (customWorkout_ != null) hash ^= CustomWorkout.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (Format != 0) hash ^= Format.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GUID.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(GUID);
      }
      if (customWorkout_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CustomWorkout);
      }
      if (Version != 0) {
        output.WriteRawTag(192, 62);
        output.WriteUInt32(Version);
      }
      if (Format != 0) {
        output.WriteRawTag(208, 62);
        output.WriteUInt32(Format);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GUID.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(GUID);
      }
      if (customWorkout_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CustomWorkout);
      }
      if (Version != 0) {
        output.WriteRawTag(192, 62);
        output.WriteUInt32(Version);
      }
      if (Format != 0) {
        output.WriteRawTag(208, 62);
        output.WriteUInt32(Format);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GUID);
      }
      if (customWorkout_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomWorkout);
      }
      if (Version != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Version);
      }
      if (Format != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Format);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkoutBinary other) {
      if (other == null) {
        return;
      }
      if (other.GUID.Length != 0) {
        GUID = other.GUID;
      }
      if (other.customWorkout_ != null) {
        if (customWorkout_ == null) {
          CustomWorkout = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout();
        }
        CustomWorkout.MergeFrom(other.CustomWorkout);
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.Format != 0) {
        Format = other.Format;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 74: {
            GUID = input.ReadString();
            break;
          }
          case 90: {
            if (customWorkout_ == null) {
              CustomWorkout = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout();
            }
            input.ReadMessage(CustomWorkout);
            break;
          }
          case 8000: {
            Version = input.ReadUInt32();
            break;
          }
          case 8016: {
            Format = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 74: {
            GUID = input.ReadString();
            break;
          }
          case 90: {
            if (customWorkout_ == null) {
              CustomWorkout = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout();
            }
            input.ReadMessage(CustomWorkout);
            break;
          }
          case 8000: {
            Version = input.ReadUInt32();
            break;
          }
          case 8016: {
            Format = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
