// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/WorkoutGoal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout {

  /// <summary>Holder for reflection information generated from CustomWorkout/WorkoutGoal.proto</summary>
  internal static partial class WorkoutGoalReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/WorkoutGoal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkoutGoalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9DdXN0b21Xb3Jrb3V0L1dvcmtvdXRHb2FsLnByb3RvIpUECgtXb3Jrb3V0",
            "R29hbBIoCglnb2FsX3R5cGUYASABKA4yFS5Xb3Jrb3V0R29hbC5Hb2FsVHlw",
            "ZRIoCgl0aW1lX2dvYWwYAiABKAsyFS5Xb3Jrb3V0R29hbC5UaW1lR29hbBIw",
            "Cg1kaXN0YW5jZV9nb2FsGAQgASgLMhkuV29ya291dEdvYWwuRGlzdGFuY2VH",
            "b2FsGpsBCghUaW1lR29hbBI1Cgl1bml0X3R5cGUYASABKA4yIi5Xb3Jrb3V0",
            "R29hbC5UaW1lR29hbC5UaW1lVW5pdFR5cGUSEgoKdW5pdF92YWx1ZRgCIAEo",
            "ASJECgxUaW1lVW5pdFR5cGUSDwoLVU5TUEVDSUZJRUQQABILCgdTRUNPTkRT",
            "EAESCwoHTUlOVVRFUxACEgkKBUhPVVJTEAMaogEKDERpc3RhbmNlR29hbBI9",
            "Cgl1bml0X3R5cGUYASABKA4yKi5Xb3Jrb3V0R29hbC5EaXN0YW5jZUdvYWwu",
            "RGlzdGFuY2VVbml0VHlwZRISCgp1bml0X3ZhbHVlGAIgASgBIj8KEERpc3Rh",
            "bmNlVW5pdFR5cGUSDwoLVU5TUEVDSUZJRUQQABIKCgZNRVRFUlMQARIOCgpL",
            "SUxPTUVURVJTEAIiPQoIR29hbFR5cGUSDwoLVU5TUEVDSUZJRUQQABIICgRU",
            "SU1FEAESDAoIRElTVEFOQ0UQAxIICgRPUEVOEARCKqoCJ0RvdG5ldFdvcmtv",
            "dXRLaXQuUHJvdG9idWYuQ3VzdG9tV29ya291dGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal), global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Parser, new[]{ "GoalType", "TimeGoal", "DistanceGoal" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal), global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Parser, new[]{ "UnitType", "UnitValue" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal), global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Parser, new[]{ "UnitType", "UnitValue" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class WorkoutGoal : pb::IMessage<WorkoutGoal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkoutGoal> _parser = new pb::MessageParser<WorkoutGoal>(() => new WorkoutGoal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkoutGoal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutGoal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutGoal(WorkoutGoal other) : this() {
      goalType_ = other.goalType_;
      timeGoal_ = other.timeGoal_ != null ? other.timeGoal_.Clone() : null;
      distanceGoal_ = other.distanceGoal_ != null ? other.distanceGoal_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutGoal Clone() {
      return new WorkoutGoal(this);
    }

    /// <summary>Field number for the "goal_type" field.</summary>
    public const int GoalTypeFieldNumber = 1;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType goalType_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified;
    /// <summary>
    /// GoalType
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType GoalType {
      get { return goalType_; }
      set {
        goalType_ = value;
      }
    }

    /// <summary>Field number for the "time_goal" field.</summary>
    public const int TimeGoalFieldNumber = 2;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal timeGoal_;
    /// <summary>
    /// Time goal (if goal_type == 1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal TimeGoal {
      get { return timeGoal_; }
      set {
        timeGoal_ = value;
      }
    }

    /// <summary>Field number for the "distance_goal" field.</summary>
    public const int DistanceGoalFieldNumber = 4;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal distanceGoal_;
    /// <summary>
    /// Distance goal (if goal_type == 3)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal DistanceGoal {
      get { return distanceGoal_; }
      set {
        distanceGoal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkoutGoal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkoutGoal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GoalType != other.GoalType) return false;
      if (!object.Equals(TimeGoal, other.TimeGoal)) return false;
      if (!object.Equals(DistanceGoal, other.DistanceGoal)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GoalType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified) hash ^= GoalType.GetHashCode();
      if (timeGoal_ != null) hash ^= TimeGoal.GetHashCode();
      if (distanceGoal_ != null) hash ^= DistanceGoal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GoalType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GoalType);
      }
      if (timeGoal_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TimeGoal);
      }
      if (distanceGoal_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DistanceGoal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GoalType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GoalType);
      }
      if (timeGoal_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TimeGoal);
      }
      if (distanceGoal_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DistanceGoal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GoalType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GoalType);
      }
      if (timeGoal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeGoal);
      }
      if (distanceGoal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DistanceGoal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkoutGoal other) {
      if (other == null) {
        return;
      }
      if (other.GoalType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType.Unspecified) {
        GoalType = other.GoalType;
      }
      if (other.timeGoal_ != null) {
        if (timeGoal_ == null) {
          TimeGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal();
        }
        TimeGoal.MergeFrom(other.TimeGoal);
      }
      if (other.distanceGoal_ != null) {
        if (distanceGoal_ == null) {
          DistanceGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal();
        }
        DistanceGoal.MergeFrom(other.DistanceGoal);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GoalType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType) input.ReadEnum();
            break;
          }
          case 18: {
            if (timeGoal_ == null) {
              TimeGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal();
            }
            input.ReadMessage(TimeGoal);
            break;
          }
          case 34: {
            if (distanceGoal_ == null) {
              DistanceGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal();
            }
            input.ReadMessage(DistanceGoal);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GoalType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.GoalType) input.ReadEnum();
            break;
          }
          case 18: {
            if (timeGoal_ == null) {
              TimeGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal();
            }
            input.ReadMessage(TimeGoal);
            break;
          }
          case 34: {
            if (distanceGoal_ == null) {
              DistanceGoal = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal();
            }
            input.ReadMessage(DistanceGoal);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the WorkoutGoal message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      internal enum GoalType {
        /// <summary>
        /// Default value
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("TIME")] Time = 1,
        [pbr::OriginalName("DISTANCE")] Distance = 3,
        [pbr::OriginalName("OPEN")] Open = 4,
      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class TimeGoal : pb::IMessage<TimeGoal>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TimeGoal> _parser = new pb::MessageParser<TimeGoal>(() => new TimeGoal());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TimeGoal> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeGoal() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeGoal(TimeGoal other) : this() {
          unitType_ = other.unitType_;
          unitValue_ = other.unitValue_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TimeGoal Clone() {
          return new TimeGoal(this);
        }

        /// <summary>Field number for the "unit_type" field.</summary>
        public const int UnitTypeFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType unitType_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified;
        /// <summary>
        /// TimeUnitType
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType UnitType {
          get { return unitType_; }
          set {
            unitType_ = value;
          }
        }

        /// <summary>Field number for the "unit_value" field.</summary>
        public const int UnitValueFieldNumber = 2;
        private double unitValue_;
        /// <summary>
        /// Time in units
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double UnitValue {
          get { return unitValue_; }
          set {
            unitValue_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TimeGoal);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TimeGoal other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UnitType != other.UnitType) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UnitValue, other.UnitValue)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified) hash ^= UnitType.GetHashCode();
          if (UnitValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UnitValue);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) UnitType);
          }
          if (UnitValue != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(UnitValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) UnitType);
          }
          if (UnitValue != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(UnitValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnitType);
          }
          if (UnitValue != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TimeGoal other) {
          if (other == null) {
            return;
          }
          if (other.UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType.Unspecified) {
            UnitType = other.UnitType;
          }
          if (other.UnitValue != 0D) {
            UnitValue = other.UnitValue;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UnitType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType) input.ReadEnum();
                break;
              }
              case 17: {
                UnitValue = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UnitType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.TimeGoal.Types.TimeUnitType) input.ReadEnum();
                break;
              }
              case 17: {
                UnitValue = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the TimeGoal message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          internal enum TimeUnitType {
            /// <summary>
            /// Default value
            /// </summary>
            [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
            [pbr::OriginalName("SECONDS")] Seconds = 1,
            [pbr::OriginalName("MINUTES")] Minutes = 2,
            [pbr::OriginalName("HOURS")] Hours = 3,
          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class DistanceGoal : pb::IMessage<DistanceGoal>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<DistanceGoal> _parser = new pb::MessageParser<DistanceGoal>(() => new DistanceGoal());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<DistanceGoal> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DistanceGoal() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DistanceGoal(DistanceGoal other) : this() {
          unitType_ = other.unitType_;
          unitValue_ = other.unitValue_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DistanceGoal Clone() {
          return new DistanceGoal(this);
        }

        /// <summary>Field number for the "unit_type" field.</summary>
        public const int UnitTypeFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType unitType_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified;
        /// <summary>
        /// DistanceUnitType
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType UnitType {
          get { return unitType_; }
          set {
            unitType_ = value;
          }
        }

        /// <summary>Field number for the "unit_value" field.</summary>
        public const int UnitValueFieldNumber = 2;
        private double unitValue_;
        /// <summary>
        /// Distance in units
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double UnitValue {
          get { return unitValue_; }
          set {
            unitValue_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as DistanceGoal);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(DistanceGoal other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UnitType != other.UnitType) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UnitValue, other.UnitValue)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified) hash ^= UnitType.GetHashCode();
          if (UnitValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UnitValue);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) UnitType);
          }
          if (UnitValue != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(UnitValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) UnitType);
          }
          if (UnitValue != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(UnitValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnitType);
          }
          if (UnitValue != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(DistanceGoal other) {
          if (other == null) {
            return;
          }
          if (other.UnitType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType.Unspecified) {
            UnitType = other.UnitType;
          }
          if (other.UnitValue != 0D) {
            UnitValue = other.UnitValue;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UnitType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType) input.ReadEnum();
                break;
              }
              case 17: {
                UnitValue = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UnitType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutGoal.Types.DistanceGoal.Types.DistanceUnitType) input.ReadEnum();
                break;
              }
              case 17: {
                UnitValue = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the DistanceGoal message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          internal enum DistanceUnitType {
            /// <summary>
            /// Default value
            /// </summary>
            [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
            [pbr::OriginalName("METERS")] Meters = 1,
            [pbr::OriginalName("KILOMETERS")] Kilometers = 2,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
