// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/CustomWorkout.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout {

  /// <summary>Holder for reflection information generated from CustomWorkout/CustomWorkout.proto</summary>
  public static partial class CustomWorkoutReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/CustomWorkout.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CustomWorkoutReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFDdXN0b21Xb3Jrb3V0L0N1c3RvbVdvcmtvdXQucHJvdG8aEVdvcmtvdXRT",
            "dGVwLnByb3RvGhNJbnRlcnZhbEJsb2NrLnByb3RvIq4DCg1DdXN0b21Xb3Jr",
            "b3V0EjIKDWFjdGl2aXR5X3R5cGUYASABKA4yGy5DdXN0b21Xb3Jrb3V0LkFj",
            "dGl2aXR5VHlwZRIyCg1sb2NhdGlvbl90eXBlGAIgASgOMhsuQ3VzdG9tV29y",
            "a291dC5Mb2NhdGlvblR5cGUSGQoMZGlzcGxheV9uYW1lGAMgASgJSACIAQES",
            "IQoGd2FybXVwGAQgASgLMgwuV29ya291dFN0ZXBIAYgBARInCg9pbnRlcnZh",
            "bF9ibG9ja3MYBSADKAsyDi5JbnRlcnZhbEJsb2NrEiMKCGNvb2xkb3duGAYg",
            "ASgLMgwuV29ya291dFN0ZXBIAogBASI5CgxBY3Rpdml0eVR5cGUSHAoYVU5T",
            "UEVDSUZJRURfQWN0aXZpdHlUeXBlEAASCwoHUlVOTklORxAlIkUKDExvY2F0",
            "aW9uVHlwZRIcChhVTlNQRUNJRklFRF9Mb2NhdGlvblR5cGUQABIKCgZJTkRP",
            "T1IQAhILCgdPVVRET09SEANCDwoNX2Rpc3BsYXlfbmFtZUIJCgdfd2FybXVw",
            "QgsKCV9jb29sZG93bkIqqgInRG90bmV0V29ya291dEtpdC5Qcm90b2J1Zi5D",
            "dXN0b21Xb3Jrb3V0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStepReflection.Descriptor, global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlockReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout), global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Parser, new[]{ "ActivityType", "LocationType", "DisplayName", "Warmup", "IntervalBlocks", "Cooldown" }, new[]{ "DisplayName", "Warmup", "Cooldown" }, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType), typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CustomWorkout : pb::IMessage<CustomWorkout>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CustomWorkout> _parser = new pb::MessageParser<CustomWorkout>(() => new CustomWorkout());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CustomWorkout> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkoutReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomWorkout() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomWorkout(CustomWorkout other) : this() {
      activityType_ = other.activityType_;
      locationType_ = other.locationType_;
      displayName_ = other.displayName_;
      warmup_ = other.warmup_ != null ? other.warmup_.Clone() : null;
      intervalBlocks_ = other.intervalBlocks_.Clone();
      cooldown_ = other.cooldown_ != null ? other.cooldown_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomWorkout Clone() {
      return new CustomWorkout(this);
    }

    /// <summary>Field number for the "activity_type" field.</summary>
    public const int ActivityTypeFieldNumber = 1;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType activityType_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType;
    /// <summary>
    /// ActivityType
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType ActivityType {
      get { return activityType_; }
      set {
        activityType_ = value;
      }
    }

    /// <summary>Field number for the "location_type" field.</summary>
    public const int LocationTypeFieldNumber = 2;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType locationType_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType;
    /// <summary>
    /// LocationType
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType LocationType {
      get { return locationType_; }
      set {
        locationType_ = value;
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 3;
    private readonly static string DisplayNameDefaultValue = "";

    private string displayName_;
    /// <summary>
    /// DisplayName (optional)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_ ?? DisplayNameDefaultValue; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "display_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDisplayName {
      get { return displayName_ != null; }
    }
    /// <summary>Clears the value of the "display_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDisplayName() {
      displayName_ = null;
    }

    /// <summary>Field number for the "warmup" field.</summary>
    public const int WarmupFieldNumber = 4;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep warmup_;
    /// <summary>
    /// Warmup (optional)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep Warmup {
      get { return warmup_; }
      set {
        warmup_ = value;
      }
    }

    /// <summary>Field number for the "interval_blocks" field.</summary>
    public const int IntervalBlocksFieldNumber = 5;
    private static readonly pb::FieldCodec<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock> _repeated_intervalBlocks_codec
        = pb::FieldCodec.ForMessage(42, global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock.Parser);
    private readonly pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock> intervalBlocks_ = new pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock>();
    /// <summary>
    /// IntervalBlock
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DotnetWorkoutKit.Protobuf.CustomWorkout.IntervalBlock> IntervalBlocks {
      get { return intervalBlocks_; }
    }

    /// <summary>Field number for the "cooldown" field.</summary>
    public const int CooldownFieldNumber = 6;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep cooldown_;
    /// <summary>
    /// Cooldown (optional)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep Cooldown {
      get { return cooldown_; }
      set {
        cooldown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CustomWorkout);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CustomWorkout other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivityType != other.ActivityType) return false;
      if (LocationType != other.LocationType) return false;
      if (DisplayName != other.DisplayName) return false;
      if (!object.Equals(Warmup, other.Warmup)) return false;
      if(!intervalBlocks_.Equals(other.intervalBlocks_)) return false;
      if (!object.Equals(Cooldown, other.Cooldown)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivityType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType) hash ^= ActivityType.GetHashCode();
      if (LocationType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType) hash ^= LocationType.GetHashCode();
      if (HasDisplayName) hash ^= DisplayName.GetHashCode();
      if (warmup_ != null) hash ^= Warmup.GetHashCode();
      hash ^= intervalBlocks_.GetHashCode();
      if (cooldown_ != null) hash ^= Cooldown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActivityType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActivityType);
      }
      if (LocationType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) LocationType);
      }
      if (HasDisplayName) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      if (warmup_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Warmup);
      }
      intervalBlocks_.WriteTo(output, _repeated_intervalBlocks_codec);
      if (cooldown_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Cooldown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActivityType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ActivityType);
      }
      if (LocationType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) LocationType);
      }
      if (HasDisplayName) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      if (warmup_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Warmup);
      }
      intervalBlocks_.WriteTo(ref output, _repeated_intervalBlocks_codec);
      if (cooldown_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Cooldown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActivityType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActivityType);
      }
      if (LocationType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LocationType);
      }
      if (HasDisplayName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (warmup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Warmup);
      }
      size += intervalBlocks_.CalculateSize(_repeated_intervalBlocks_codec);
      if (cooldown_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cooldown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CustomWorkout other) {
      if (other == null) {
        return;
      }
      if (other.ActivityType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType.UnspecifiedActivityType) {
        ActivityType = other.ActivityType;
      }
      if (other.LocationType != global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType.UnspecifiedLocationType) {
        LocationType = other.LocationType;
      }
      if (other.HasDisplayName) {
        DisplayName = other.DisplayName;
      }
      if (other.warmup_ != null) {
        if (warmup_ == null) {
          Warmup = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
        }
        Warmup.MergeFrom(other.Warmup);
      }
      intervalBlocks_.Add(other.intervalBlocks_);
      if (other.cooldown_ != null) {
        if (cooldown_ == null) {
          Cooldown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
        }
        Cooldown.MergeFrom(other.Cooldown);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActivityType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType) input.ReadEnum();
            break;
          }
          case 16: {
            LocationType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType) input.ReadEnum();
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            if (warmup_ == null) {
              Warmup = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
            }
            input.ReadMessage(Warmup);
            break;
          }
          case 42: {
            intervalBlocks_.AddEntriesFrom(input, _repeated_intervalBlocks_codec);
            break;
          }
          case 50: {
            if (cooldown_ == null) {
              Cooldown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
            }
            input.ReadMessage(Cooldown);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActivityType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.ActivityType) input.ReadEnum();
            break;
          }
          case 16: {
            LocationType = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.CustomWorkout.Types.LocationType) input.ReadEnum();
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            if (warmup_ == null) {
              Warmup = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
            }
            input.ReadMessage(Warmup);
            break;
          }
          case 42: {
            intervalBlocks_.AddEntriesFrom(ref input, _repeated_intervalBlocks_codec);
            break;
          }
          case 50: {
            if (cooldown_ == null) {
              Cooldown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.WorkoutStep();
            }
            input.ReadMessage(Cooldown);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CustomWorkout message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ActivityType {
        /// <summary>
        /// Default value
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED_ActivityType")] UnspecifiedActivityType = 0,
        [pbr::OriginalName("RUNNING")] Running = 37,
      }

      public enum LocationType {
        /// <summary>
        /// Default value
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED_LocationType")] UnspecifiedLocationType = 0,
        [pbr::OriginalName("INDOOR")] Indoor = 2,
        [pbr::OriginalName("OUTDOOR")] Outdoor = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
