// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/Alert/SpeedAlert.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout.Alert {

  /// <summary>Holder for reflection information generated from CustomWorkout/Alert/SpeedAlert.proto</summary>
  public static partial class SpeedAlertReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/Alert/SpeedAlert.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpeedAlertReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRDdXN0b21Xb3Jrb3V0L0FsZXJ0L1NwZWVkQWxlcnQucHJvdG8i1wMKClNw",
            "ZWVkQWxlcnQSNgoRc3BlZWRfcmFuZ2VfYWxlcnQYAiABKAsyGy5TcGVlZEFs",
            "ZXJ0LlNwZWVkUmFuZ2VBbGVydBprCg9TcGVlZFJhbmdlQWxlcnQSKwoLbG93",
            "ZXJfYm91bmQYASABKAsyFi5TcGVlZEFsZXJ0LlNwZWVkQm91bmQSKwoLdXBw",
            "ZXJfYm91bmQYAiABKAsyFi5TcGVlZEFsZXJ0LlNwZWVkQm91bmQaZwoKU3Bl",
            "ZWRCb3VuZBIgCgVzcGVlZBgBIAEoCzIRLlNwZWVkQWxlcnQuU3BlZWQSNwoH",
            "dW5rbm93bhgCIAEoCzImLlNwZWVkQWxlcnQuVW5rbm93bl9XcmFwVUludDMy",
            "X0ZpeGVkNjQafgoFU3BlZWQSLQoEdW5pdBgBIAEoDjIfLlNwZWVkQWxlcnQu",
            "U3BlZWQuU3BlZWRVbml0RW51bRINCgVzcGVlZBgCIAEoASI3Cg1TcGVlZFVu",
            "aXRFbnVtEg8KC1VOU1BFQ0lGSUVEEAASFQoRTUVURVJTX1BFUl9TRUNPTkQQ",
            "ARo7ChpVbmtub3duX1dyYXBVSW50MzJfRml4ZWQ2NBINCgVmaXJzdBgBIAEo",
            "DRIOCgZzZWNvbmQYAiABKAFCMKoCLURvdG5ldFdvcmtvdXRLaXQuUHJvdG9i",
            "dWYuQ3VzdG9tV29ya291dC5BbGVydGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Parser, new[]{ "SpeedRangeAlert" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert.Parser, new[]{ "LowerBound", "UpperBound" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound.Parser, new[]{ "Speed", "Unknown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Parser, new[]{ "Unit", "Speed_" }, null, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64.Parser, new[]{ "First", "Second" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpeedAlert : pb::IMessage<SpeedAlert>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpeedAlert> _parser = new pb::MessageParser<SpeedAlert>(() => new SpeedAlert());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpeedAlert> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlertReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpeedAlert() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpeedAlert(SpeedAlert other) : this() {
      speedRangeAlert_ = other.speedRangeAlert_ != null ? other.speedRangeAlert_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpeedAlert Clone() {
      return new SpeedAlert(this);
    }

    /// <summary>Field number for the "speed_range_alert" field.</summary>
    public const int SpeedRangeAlertFieldNumber = 2;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert speedRangeAlert_;
    /// <summary>
    /// SpeedRangeAlert
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert SpeedRangeAlert {
      get { return speedRangeAlert_; }
      set {
        speedRangeAlert_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpeedAlert);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpeedAlert other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SpeedRangeAlert, other.SpeedRangeAlert)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (speedRangeAlert_ != null) hash ^= SpeedRangeAlert.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (speedRangeAlert_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpeedRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (speedRangeAlert_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpeedRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (speedRangeAlert_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpeedRangeAlert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpeedAlert other) {
      if (other == null) {
        return;
      }
      if (other.speedRangeAlert_ != null) {
        if (speedRangeAlert_ == null) {
          SpeedRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert();
        }
        SpeedRangeAlert.MergeFrom(other.SpeedRangeAlert);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (speedRangeAlert_ == null) {
              SpeedRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert();
            }
            input.ReadMessage(SpeedRangeAlert);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (speedRangeAlert_ == null) {
              SpeedRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedRangeAlert();
            }
            input.ReadMessage(SpeedRangeAlert);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SpeedAlert message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class SpeedRangeAlert : pb::IMessage<SpeedRangeAlert>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SpeedRangeAlert> _parser = new pb::MessageParser<SpeedRangeAlert>(() => new SpeedRangeAlert());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SpeedRangeAlert> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedRangeAlert() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedRangeAlert(SpeedRangeAlert other) : this() {
          lowerBound_ = other.lowerBound_ != null ? other.lowerBound_.Clone() : null;
          upperBound_ = other.upperBound_ != null ? other.upperBound_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedRangeAlert Clone() {
          return new SpeedRangeAlert(this);
        }

        /// <summary>Field number for the "lower_bound" field.</summary>
        public const int LowerBoundFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound lowerBound_;
        /// <summary>
        /// Lower bound
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound LowerBound {
          get { return lowerBound_; }
          set {
            lowerBound_ = value;
          }
        }

        /// <summary>Field number for the "upper_bound" field.</summary>
        public const int UpperBoundFieldNumber = 2;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound upperBound_;
        /// <summary>
        /// Upper bound
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound UpperBound {
          get { return upperBound_; }
          set {
            upperBound_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SpeedRangeAlert);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SpeedRangeAlert other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(LowerBound, other.LowerBound)) return false;
          if (!object.Equals(UpperBound, other.UpperBound)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (lowerBound_ != null) hash ^= LowerBound.GetHashCode();
          if (upperBound_ != null) hash ^= UpperBound.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (lowerBound_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LowerBound);
          }
          if (upperBound_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(UpperBound);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (lowerBound_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(LowerBound);
          }
          if (upperBound_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(UpperBound);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (lowerBound_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(LowerBound);
          }
          if (upperBound_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpperBound);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SpeedRangeAlert other) {
          if (other == null) {
            return;
          }
          if (other.lowerBound_ != null) {
            if (lowerBound_ == null) {
              LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
            }
            LowerBound.MergeFrom(other.LowerBound);
          }
          if (other.upperBound_ != null) {
            if (upperBound_ == null) {
              UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
            }
            UpperBound.MergeFrom(other.UpperBound);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (lowerBound_ == null) {
                  LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
                }
                input.ReadMessage(LowerBound);
                break;
              }
              case 18: {
                if (upperBound_ == null) {
                  UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
                }
                input.ReadMessage(UpperBound);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (lowerBound_ == null) {
                  LowerBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
                }
                input.ReadMessage(LowerBound);
                break;
              }
              case 18: {
                if (upperBound_ == null) {
                  UpperBound = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.SpeedBound();
                }
                input.ReadMessage(UpperBound);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class SpeedBound : pb::IMessage<SpeedBound>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SpeedBound> _parser = new pb::MessageParser<SpeedBound>(() => new SpeedBound());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SpeedBound> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedBound() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedBound(SpeedBound other) : this() {
          speed_ = other.speed_ != null ? other.speed_.Clone() : null;
          unknown_ = other.unknown_ != null ? other.unknown_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SpeedBound Clone() {
          return new SpeedBound(this);
        }

        /// <summary>Field number for the "speed" field.</summary>
        public const int SpeedFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed speed_;
        /// <summary>
        /// Lower bound
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed Speed {
          get { return speed_; }
          set {
            speed_ = value;
          }
        }

        /// <summary>Field number for the "unknown" field.</summary>
        public const int UnknownFieldNumber = 2;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64 unknown_;
        /// <summary>
        /// Unknown
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64 Unknown {
          get { return unknown_; }
          set {
            unknown_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SpeedBound);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SpeedBound other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Speed, other.Speed)) return false;
          if (!object.Equals(Unknown, other.Unknown)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (speed_ != null) hash ^= Speed.GetHashCode();
          if (unknown_ != null) hash ^= Unknown.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (speed_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Speed);
          }
          if (unknown_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (speed_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Speed);
          }
          if (unknown_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (speed_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Speed);
          }
          if (unknown_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SpeedBound other) {
          if (other == null) {
            return;
          }
          if (other.speed_ != null) {
            if (speed_ == null) {
              Speed = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed();
            }
            Speed.MergeFrom(other.Speed);
          }
          if (other.unknown_ != null) {
            if (unknown_ == null) {
              Unknown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64();
            }
            Unknown.MergeFrom(other.Unknown);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (speed_ == null) {
                  Speed = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed();
                }
                input.ReadMessage(Speed);
                break;
              }
              case 18: {
                if (unknown_ == null) {
                  Unknown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64();
                }
                input.ReadMessage(Unknown);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (speed_ == null) {
                  Speed = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed();
                }
                input.ReadMessage(Speed);
                break;
              }
              case 18: {
                if (unknown_ == null) {
                  Unknown = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Unknown_WrapUInt32_Fixed64();
                }
                input.ReadMessage(Unknown);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Speed : pb::IMessage<Speed>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Speed> _parser = new pb::MessageParser<Speed>(() => new Speed());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Speed> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Speed() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Speed(Speed other) : this() {
          unit_ = other.unit_;
          speed_ = other.speed_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Speed Clone() {
          return new Speed(this);
        }

        /// <summary>Field number for the "unit" field.</summary>
        public const int UnitFieldNumber = 1;
        private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum unit_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum Unit {
          get { return unit_; }
          set {
            unit_ = value;
          }
        }

        /// <summary>Field number for the "speed" field.</summary>
        public const int Speed_FieldNumber = 2;
        private double speed_;
        /// <summary>
        /// speed in m/s
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Speed_ {
          get { return speed_; }
          set {
            speed_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Speed);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Speed other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unit != other.Unit) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Speed_, other.Speed_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Unit != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified) hash ^= Unit.GetHashCode();
          if (Speed_ != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Speed_);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Unit != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Unit);
          }
          if (Speed_ != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Speed_);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Unit != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Unit);
          }
          if (Speed_ != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Speed_);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Unit != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Unit);
          }
          if (Speed_ != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Speed other) {
          if (other == null) {
            return;
          }
          if (other.Unit != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum.Unspecified) {
            Unit = other.Unit;
          }
          if (other.Speed_ != 0D) {
            Speed_ = other.Speed_;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Unit = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum) input.ReadEnum();
                break;
              }
              case 17: {
                Speed_ = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Unit = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Types.Speed.Types.SpeedUnitEnum) input.ReadEnum();
                break;
              }
              case 17: {
                Speed_ = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Speed message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum SpeedUnitEnum {
            /// <summary>
            /// Default value
            /// </summary>
            [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
            [pbr::OriginalName("METERS_PER_SECOND")] MetersPerSecond = 1,
          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Unknown_WrapUInt32_Fixed64 : pb::IMessage<Unknown_WrapUInt32_Fixed64>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Unknown_WrapUInt32_Fixed64> _parser = new pb::MessageParser<Unknown_WrapUInt32_Fixed64>(() => new Unknown_WrapUInt32_Fixed64());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Unknown_WrapUInt32_Fixed64> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert.Descriptor.NestedTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Unknown_WrapUInt32_Fixed64() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Unknown_WrapUInt32_Fixed64(Unknown_WrapUInt32_Fixed64 other) : this() {
          first_ = other.first_;
          second_ = other.second_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Unknown_WrapUInt32_Fixed64 Clone() {
          return new Unknown_WrapUInt32_Fixed64(this);
        }

        /// <summary>Field number for the "first" field.</summary>
        public const int FirstFieldNumber = 1;
        private uint first_;
        /// <summary>
        /// Unknown, always 1
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint First {
          get { return first_; }
          set {
            first_ = value;
          }
        }

        /// <summary>Field number for the "second" field.</summary>
        public const int SecondFieldNumber = 2;
        private double second_;
        /// <summary>
        /// Unknown, always 1
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Second {
          get { return second_; }
          set {
            second_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Unknown_WrapUInt32_Fixed64);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Unknown_WrapUInt32_Fixed64 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (First != other.First) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Second, other.Second)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (First != 0) hash ^= First.GetHashCode();
          if (Second != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Second);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (First != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(First);
          }
          if (Second != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Second);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (First != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(First);
          }
          if (Second != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Second);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (First != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(First);
          }
          if (Second != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Unknown_WrapUInt32_Fixed64 other) {
          if (other == null) {
            return;
          }
          if (other.First != 0) {
            First = other.First;
          }
          if (other.Second != 0D) {
            Second = other.Second;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                First = input.ReadUInt32();
                break;
              }
              case 17: {
                Second = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                First = input.ReadUInt32();
                break;
              }
              case 17: {
                Second = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
