// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomWorkout/Alert/WorkoutAlert.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotnetWorkoutKit.Protobuf.CustomWorkout.Alert {

  /// <summary>Holder for reflection information generated from CustomWorkout/Alert/WorkoutAlert.proto</summary>
  public static partial class WorkoutAlertReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomWorkout/Alert/WorkoutAlert.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkoutAlertReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZDdXN0b21Xb3Jrb3V0L0FsZXJ0L1dvcmtvdXRBbGVydC5wcm90bxoQU3Bl",
            "ZWRBbGVydC5wcm90bxoZSGVhcnRSYXRlUmFuZ2VBbGVydC5wcm90byKNAgoM",
            "V29ya291dEFsZXJ0EjMKDGFsZXJ0X21ldHJpYxgBIAEoDjIdLldvcmtvdXRB",
            "bGVydC5BbGVydE1ldHJpY0VudW0SDwoHdW5rbm93bhgCIAEoDRIiCgtzcGVl",
            "ZF9hbGVydBgEIAEoCzILLlNwZWVkQWxlcnRIABI2ChZoZWFydF9yYXRlX3Jh",
            "bmdlX2FsZXJ0GAcgASgLMhQuSGVhcnRSYXRlUmFuZ2VBbGVydEgAIlIKD0Fs",
            "ZXJ0TWV0cmljRW51bRIPCgtVTlNQRUNJRklFRBAAEgsKB0FWRVJBR0UQARIL",
            "CgdDVVJSRU5UEAISFAoQQ09VTlRfUEVSX01JTlVURRAFQgcKBWFsZXJ0QjCq",
            "Ai1Eb3RuZXRXb3Jrb3V0S2l0LlByb3RvYnVmLkN1c3RvbVdvcmtvdXQuQWxl",
            "cnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlertReflection.Descriptor, global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlertReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert), global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Parser, new[]{ "AlertMetric", "Unknown", "SpeedAlert", "HeartRateRangeAlert" }, new[]{ "Alert" }, new[]{ typeof(global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorkoutAlert : pb::IMessage<WorkoutAlert>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkoutAlert> _parser = new pb::MessageParser<WorkoutAlert>(() => new WorkoutAlert());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkoutAlert> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlertReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert(WorkoutAlert other) : this() {
      alertMetric_ = other.alertMetric_;
      unknown_ = other.unknown_;
      switch (other.AlertCase) {
        case AlertOneofCase.SpeedAlert:
          SpeedAlert = other.SpeedAlert.Clone();
          break;
        case AlertOneofCase.HeartRateRangeAlert:
          HeartRateRangeAlert = other.HeartRateRangeAlert.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkoutAlert Clone() {
      return new WorkoutAlert(this);
    }

    /// <summary>Field number for the "alert_metric" field.</summary>
    public const int AlertMetricFieldNumber = 1;
    private global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum alertMetric_ = global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum AlertMetric {
      get { return alertMetric_; }
      set {
        alertMetric_ = value;
      }
    }

    /// <summary>Field number for the "unknown" field.</summary>
    public const int UnknownFieldNumber = 2;
    private uint unknown_;
    /// <summary>
    /// Unknown, 2 = range type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unknown {
      get { return unknown_; }
      set {
        unknown_ = value;
      }
    }

    /// <summary>Field number for the "speed_alert" field.</summary>
    public const int SpeedAlertFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert SpeedAlert {
      get { return alertCase_ == AlertOneofCase.SpeedAlert ? (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert) alert_ : null; }
      set {
        alert_ = value;
        alertCase_ = value == null ? AlertOneofCase.None : AlertOneofCase.SpeedAlert;
      }
    }

    /// <summary>Field number for the "heart_rate_range_alert" field.</summary>
    public const int HeartRateRangeAlertFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert HeartRateRangeAlert {
      get { return alertCase_ == AlertOneofCase.HeartRateRangeAlert ? (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert) alert_ : null; }
      set {
        alert_ = value;
        alertCase_ = value == null ? AlertOneofCase.None : AlertOneofCase.HeartRateRangeAlert;
      }
    }

    private object alert_;
    /// <summary>Enum of possible cases for the "alert" oneof.</summary>
    public enum AlertOneofCase {
      None = 0,
      SpeedAlert = 4,
      HeartRateRangeAlert = 7,
    }
    private AlertOneofCase alertCase_ = AlertOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlertOneofCase AlertCase {
      get { return alertCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAlert() {
      alertCase_ = AlertOneofCase.None;
      alert_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkoutAlert);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkoutAlert other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AlertMetric != other.AlertMetric) return false;
      if (Unknown != other.Unknown) return false;
      if (!object.Equals(SpeedAlert, other.SpeedAlert)) return false;
      if (!object.Equals(HeartRateRangeAlert, other.HeartRateRangeAlert)) return false;
      if (AlertCase != other.AlertCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) hash ^= AlertMetric.GetHashCode();
      if (Unknown != 0) hash ^= Unknown.GetHashCode();
      if (alertCase_ == AlertOneofCase.SpeedAlert) hash ^= SpeedAlert.GetHashCode();
      if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) hash ^= HeartRateRangeAlert.GetHashCode();
      hash ^= (int) alertCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AlertMetric);
      }
      if (Unknown != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Unknown);
      }
      if (alertCase_ == AlertOneofCase.SpeedAlert) {
        output.WriteRawTag(34);
        output.WriteMessage(SpeedAlert);
      }
      if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) {
        output.WriteRawTag(58);
        output.WriteMessage(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AlertMetric);
      }
      if (Unknown != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Unknown);
      }
      if (alertCase_ == AlertOneofCase.SpeedAlert) {
        output.WriteRawTag(34);
        output.WriteMessage(SpeedAlert);
      }
      if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) {
        output.WriteRawTag(58);
        output.WriteMessage(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AlertMetric);
      }
      if (Unknown != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unknown);
      }
      if (alertCase_ == AlertOneofCase.SpeedAlert) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpeedAlert);
      }
      if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeartRateRangeAlert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkoutAlert other) {
      if (other == null) {
        return;
      }
      if (other.AlertMetric != global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum.Unspecified) {
        AlertMetric = other.AlertMetric;
      }
      if (other.Unknown != 0) {
        Unknown = other.Unknown;
      }
      switch (other.AlertCase) {
        case AlertOneofCase.SpeedAlert:
          if (SpeedAlert == null) {
            SpeedAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
          }
          SpeedAlert.MergeFrom(other.SpeedAlert);
          break;
        case AlertOneofCase.HeartRateRangeAlert:
          if (HeartRateRangeAlert == null) {
            HeartRateRangeAlert = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
          }
          HeartRateRangeAlert.MergeFrom(other.HeartRateRangeAlert);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AlertMetric = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) input.ReadEnum();
            break;
          }
          case 16: {
            Unknown = input.ReadUInt32();
            break;
          }
          case 34: {
            global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert subBuilder = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
            if (alertCase_ == AlertOneofCase.SpeedAlert) {
              subBuilder.MergeFrom(SpeedAlert);
            }
            input.ReadMessage(subBuilder);
            SpeedAlert = subBuilder;
            break;
          }
          case 58: {
            global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert subBuilder = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
            if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) {
              subBuilder.MergeFrom(HeartRateRangeAlert);
            }
            input.ReadMessage(subBuilder);
            HeartRateRangeAlert = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AlertMetric = (global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.WorkoutAlert.Types.AlertMetricEnum) input.ReadEnum();
            break;
          }
          case 16: {
            Unknown = input.ReadUInt32();
            break;
          }
          case 34: {
            global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert subBuilder = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.SpeedAlert();
            if (alertCase_ == AlertOneofCase.SpeedAlert) {
              subBuilder.MergeFrom(SpeedAlert);
            }
            input.ReadMessage(subBuilder);
            SpeedAlert = subBuilder;
            break;
          }
          case 58: {
            global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert subBuilder = new global::DotnetWorkoutKit.Protobuf.CustomWorkout.Alert.HeartRateRangeAlert();
            if (alertCase_ == AlertOneofCase.HeartRateRangeAlert) {
              subBuilder.MergeFrom(HeartRateRangeAlert);
            }
            input.ReadMessage(subBuilder);
            HeartRateRangeAlert = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the WorkoutAlert message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AlertMetricEnum {
        /// <summary>
        /// Default value
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("AVERAGE")] Average = 1,
        [pbr::OriginalName("CURRENT")] Current = 2,
        [pbr::OriginalName("COUNT_PER_MINUTE")] CountPerMinute = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
