name: Build and Publish NuGet Package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DotnetWorkoutKit

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Get VersionPrefix
        id: get_version_prefix
        run: echo "version_prefix=$(grep '<VersionPrefix>' DotnetWorkoutKit.csproj | sed -E 's/.*<VersionPrefix>(.*)<\/VersionPrefix>.*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Get Release Notes
        id: get_release_notes
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "release_notes<<$EOF" >> "$GITHUB_OUTPUT"
          cat RELEASE_NOTES.txt >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      
      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack -c Release -o ./nupkg /p:PackageVersion=${{ steps.get_version_prefix.outputs.version_prefix }}.${{ github.run_number }} /p:PackageReleaseNotes="${{ steps.get_release_notes.outputs.release_notes }}"

      - name: List nupkg directory contents
        run: ls -la ./nupkg

      - name: Publish to artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./DotnetWorkoutKit/nupkg/DotnetWorkoutKit.*.nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json
    